$(function(){
    $(".menu_btn").click(function(){
        $(".menu_btn").css("display","none");
        $(".close_btn").css("display","flex");
        $(".cont").fadeIn();
        $(".cont").css("position","fixed");
    });
    $(".close_btn").click(function(){
        $(".close_btn").css("display","none");
        $(".menu_btn").css("display","flex");
        $(".cont").fadeOut();
    });
    $(".cont_nav1").click(function(){
        $(".close_btn").css("display","none");
        $(".menu_btn").css("display","flex");
        $(".cont").fadeOut();
    });
    $(".cont_nav2").click(function(){
        $(".close_btn").css("display","none");
        $(".menu_btn").css("display","flex");
        $(".cont").fadeOut();
    });
    $(".cont_nav3").click(function(){
        $(".close_btn").css("display","none");
        $(".menu_btn").css("display","flex");
        $(".cont").fadeOut();
    });
    $(".cont_nav4").click(function(){
        $(".close_btn").css("display","none");
        $(".menu_btn").css("display","flex");
        $(".cont").fadeOut();
    });
    $(".cont_nav5").click(function(){
        $(".close_btn").css("display","none");
        $(".menu_btn").css("display","flex");
        $(".cont").fadeOut();
    });
});
$(function(){
    $(".sec4-1").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-1").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut(); 
       $(".sec4-h-1").fadeOut();
       $(".menu_btn").fadeIn();
    });
// sec4-1 fade In/Out
    $(".sec4-2").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-2").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut();
       $(".sec4-h-2").fadeOut(); 
       $(".menu_btn").fadeIn();
    });

    $(".sec4-3").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-3").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut();
       $(".sec4-h-3").fadeOut(); 
       $(".menu_btn").fadeIn();
    });

    $(".sec4-4").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-4").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut();
       $(".sec4-h-4").fadeOut(); 
       $(".menu_btn").fadeIn();
    });

    $(".sec4-5").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-5").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut(); 
       $(".sec4-h-5").fadeOut();
       $(".menu_btn").fadeIn();
    });

    $(".sec4-6").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-6").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut(); 
       $(".sec4-h-6").fadeOut();
       $(".menu_btn").fadeIn();
    });

    $(".sec4-7").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-7").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut(); 
       $(".sec4-h-7").fadeOut();
       $(".menu_btn").fadeIn();
    });

    $(".sec4-8").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-8").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut();
       $(".sec4-h-8").fadeOut(); 
       $(".menu_btn").fadeIn();
    });

    $(".sec4-9").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-9").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut(); 
       $(".sec4-h-9").fadeOut();
       $(".menu_btn").fadeIn();
    });

    $(".sec4-10").click(function(){
        $(".menu_btn").css("display","none");
        $(".sec4-hidden").fadeIn();
        $(".sec4-h-10").fadeIn();
    });
    $(".sec4-closebtn").click(function(){
       $(".sec4-hidden").fadeOut(); 
       $(".sec4-h-10").fadeOut();
       $(".menu_btn").fadeIn();
    });
});


    